# Generated by Django 5.2.5 on 2026-01-14 16:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_options_project_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('content', models.TextField(help_text='HTML content from rich text editor')),
                ('excerpt', models.TextField(blank=True, help_text='Short description for preview', max_length=300)),
                ('thumbnail_url', models.URLField(blank=True)),
                ('featured', models.BooleanField(default=False, help_text='Feature this blog post')),
                ('published', models.BooleanField(default=False, help_text='Publish this post')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-featured', 'order', '-created_at'],
            },
        ),
    ]
